### ISSUE TITLE
stock split will throw off the script with assertion error

### ISSUE THREAD

**Issue by nuwonda** [sbaio/rev_compile_statements#2]
Traceback (most recent call last):
  File "rev.py", line 96, in <module>
    process_file(file)
  File "rev.py", line 75, in process_file
    assert new_qte >= -1e-3, new_qte
AssertionError: -32.0

e.g. Tesla stock split on August 2020 statement will lead to assertion error for statement September 2020 as the quantity will be negative. Script would need to be able to process SSP in order to get the correct quantity, avg price etc.

**Comment by nuwonda** [comment]
Sorry if this is the wrong place. Would any of you be able to have a look and see if SSP can be included so the script can calculate stock splits? @sbaio @otossbai @mehdichaouch thanks!

**Comment by sbaio** [comment]
Can you show a screenshot of a stock split transaction ?

**Comment by nuwonda** [comment]
sure. 
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/16824449/120838835-8eeb7b80-c568-11eb-9a4b-429ce3b65946.png">

ACTIVITY
Trade Date Settle Date Currency Activity Type Symbol / Description Quantity Price Amount
07/06/2020 06/12/2020 USD SSP TSLA - TESLA INC COM - CA-SSP. Surrender old shs. -8 1118.14 0.00
07/06/2020 06/12/2020 USD SSP TSLA - TESLA INC COM - CA-SSP. Add New shs.(TSLA:1->5) 40 223.628 0.00

**Comment by nuwonda** [comment]
basically the first SSP line reduces amount to 0 (had 8, so -8) and second SSP line has the new amount of shares and their new price per share value. Amount shows 0 as it's not a buy/sell.
@sbaio btw you can also get the trade confirmation of each trade as pdfs from drivewealth dashboard directly which will include the fees (not included in the monthly rev statements). login here: https://client.drivewealth.com/login (use last part of your revolut account number as drivewealth account number, i.e. REVO-001-XXXXXX, just the XXXX... part).

**Comment by nuwonda** [comment]
@sbaio do you need any more info?
